spring.application.name=TechAlert

feign.client.config.default.loggerLevel=full

logging.level.com.rest_client.aplicacao=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.feign=DEBUG

spring.devtools.restart.enabled=true